[versions]
minecraft = "1.21.1"
parchment-minecraft = "1.21.1"
parchment-mappings = "2024.11.17"

architectury = "13.0.11"

fabric-loader = "0.19.3"
fabric-api = "0.116.15+1.21.1"

fabric-forgeConfigPort = "21.1.6"
fabric-tooltipfix = "1.1.1-1.20"

neoforge-platform = "21.1.248"
neoforge-loader = "4"

[plugins]
loom = { id = "dev.architectury.loom", version = "1.11-SNAPSHOT" }
architectury = { id = "architectury-plugin", version = "3.4-SNAPSHOT" }
shadow = { id = "com.gradleup.shadow", version = "9.4.1" }
spotless = { id = "com.diffplug.spotless", version = "6.22.0" }

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
architectury-api = { group = "dev.architectury", name = "architectury", version.ref = "architectury" }

# Fabric specific libraries
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
fabric-architectury = { group = "dev.architectury", name = "architectury-fabric", version.ref = "architectury" }

fabric-forgeConfigPort = { group = "fuzs.forgeconfigapiport", name = "forgeconfigapiport-fabric", version.ref = "fabric-forgeConfigPort" }
fabric-energy = { group = "teamreborn", name = "energy", version = "4.1.0" }

fabric-tooltipFix = { group = "maven.modrinth", name = "tooltipfix", version.ref = "fabric-tooltipfix" }
fabric-roughlyEnoughItems = { group = "me.shedaniel", name = "RoughlyEnoughItems-fabric", version = "16.0.799" }

neoforge-platform = { group = "net.neoforged", name = "neoforge", version.ref = "neoforge-platform" }
neoforge-architectury = { group = "dev.architectury", name = "architectury-neoforge", version.ref = "architectury" }
