@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package li.cil.scannable.integration.industrialcraft2;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;